### ISSUE TITLE
"it should be a large links visible" typo

### ISSUE THREAD

**Issue by wdoekes** [ossobv/exactonline#14]

**Comment by vilitux** [comment]
this affects me too

**Comment by Urth** [comment]
I have noticed this as well, it is really annoying me.
When will this be fixed?

**Comment by wdoekes** [comment]
I've locked this thread because of the overwhelming response.

No need to comment on this any more. I've moved this issue to the:
https://memegenerator.net/instance/76807880/dr-evil-meme-priority-queue

**Comment by wdoekes** [comment]
Closed by 182934a64507e5e2ae94c33b70892a529289f8c7.
