### ISSUE TITLE
ValueError: Iteration 50 limit reached! Last resource...

### ISSUE THREAD

**Issue by gvisniuc** [ossobv/exactonline#22]
Hi,

I am trying to fetch a long list of  `TransactionLines` but for certain large date intervals I receive an error regarding iteration limits.

`ValueError: Iteration 50 limit reached!`

The code responsible for this can be found at https://github.com/ossobv/exactonline/blob/182934a64507e5e2ae94c33b70892a529289f8c7/exactonline/api/unwrap.py#L18

Is there any specific reason for the value `50` and if no would it be possible to make it a configurable parameter?

Regards,
G

**Comment by wdoekes** [comment]
No specific reason. Just a safe-guard in case something was wrong and the code went into a loop.

PRs are welcome.

**Comment by gvisniuc** [comment]
Sounds good, I've created a PR with the suggested changes, let me know what you think.

https://github.com/ossobv/exactonline/pull/23
