### ISSUE TITLE
ExactOnline reports refresh token reuse

### ISSUE THREAD

**Issue by LordGaav** [ossobv/exactonline#27]
I've received a message that we're reusing refresh tokens, which is a behaviour which will not be supported after 31 December. I'm unable to find a source for this reuse however.

The access_expiry field and refresh_token field seem to be properly updated in the INI file. I can see this happening when starting the application, but I'm unsure if this happens while the application is running. Checking the code, it seems the `AutoRefresh` class should handle requesting and setting new tokens.

The only other thing I can think of is that my application is long running (think months). Maybe the token gets written to the INI file, but doesn't actually get updated in memory?

I'm running in the official Python 3.5.5 Docker image with exactonline 0.3.2 . I know I'm a few versions behind, but I saw no relevant changes (apart from a refactor).

**Comment by wdoekes** [comment]
Hi. I've had a report of someone else with the same problem. In his case, it turned out that he was he was using multiple instances:

> Ik heb mijn python code nagelopen en het blijkt dat ik in meerdere functies binnen mijn programma, onder andere in de onderstaande, het volgende steeds deed:
```
def find_Name(division): 
    api=get_api()
    request = 'v1/12345/system/Divisions?$select=Code,Hid,Description'
    resp=api.rest(GET(request))
   ...................
```
> De api werd hierdoor meerdere keren geopend!
> 
> Ik heb api=get_api() uit alle functies gehaald en in main het volgende gedaan:
>
> #open api global omdat api in diverse functies wordt gebruikt (anders wordt api steeds opnieuw geopend met niet ververste refresh codes en dat vind Exact kennelijk niet leuk)
```
    global api
    api = get_api()
```
> _Dit werkt nu goed en de api wordt tijdens de duur van mijn programma  (minder dan 1 minuut runtime) nu slechts eenmaal aangeroepen/geopend._
> 
> Globaal zaken definiëren is in het algemeen een slechte zaak, maar ik het nu even geen andere oplossing.
>
> Hartelijk dank zover.

(my emphasis)

Maybe you're dealing with the same cause?

**Comment by LordGaav** [comment]
I've tried to avoid creating multiple API instances using a classmethod / variable, but I'm going to make sure tomorrow because I realize now that this class is subclassed and there might be ~10 different API instances. Thanks for the pointer.

**Comment by xonda** [comment]
Hi! We've got the same notification from Exact for one of our projects. Could you please advice if we need extra actions in this case or "exactonline" lib should handle tokens itself properly? Seems like there were no updates lately concerning token reuse
Thanks in advance,

**Comment by wdoekes** [comment]
> Seems like there were no updates lately concerning token reuse

There are no commits, because there are no problems :trollface: 

After the quoted commenter mailed, I examined, and found no issues. Tokens get refreshed as they should. But if you're loading multiple API-instances with old INI data, I suspect you're causing trouble for yourself.

_I suggest you don't do that._

Please come back when you have more information that points to a real problem in the API.

**Comment by LordGaav** [comment]
The relevant parts of my code were:

```diff
     @classmethod
     def connect(cls, dryrun=False, force_sync=False):
-        if not cls.exact_api:
-            cls.exact_api = get_exactonline_client()
+        if not hasattr(ExactOnlineDestination, "exact_api"):
+            ExactOnlineDestination.exact_api = get_exactonline_client()
```

The old code would create a new exact_api for every subclass. The new code will set the exact_api explicitly on the parent class, and every call that wants to use it goes through a method that calls the parent class.

I'll report back if this fixes the problem. @wdoekes : you may want to think about making this a bit easier to use, for example making the INI storage a singleton or something. Alternatively, explicitly mention this in the docs for the storage.

**Comment by wdoekes** [comment]
Does this resolve your issues?

**Comment by LordGaav** [comment]
I haven't had any notifications from ExactOnline that we're still doing it wrong. I'll close this issue for now.

Thanks for the input and fixes.
