### ISSUE TITLE
How to add/make use of more Exact online API's?

### ISSUE THREAD

**Issue by RubenvZenden** [ossobv/exactonline#31]
Hi guys, I am a beginner in Python and wonder if it is possible to create more python scripts that GET data from the Exact Online API for example "finance/GLClassifications"? Can someone explain to me what steps I have to take? 
I already made a script (based on `ledgeraccounts.py`) and wanted to test if this script works. Unfortunately, I get the `AttributeError: "ExactAPI" object has no attribute "glclassifications"`. In the `__init__` script I added `from .glclassifications import GLClassifications` and `glclassifications = GLClassifications.as_property()` on the appropriate places in the script.

It is probably good to know that the additions on the script I have done locally on my computer and that I am using anaconda.

**Comment by wdoekes** [comment]
It sounds like you did the right things.

But this error seems fishy:
```
AttributeError: "ExactAPI" object has no attribute
```
There is no `ExactAPI`, but there is an `ExactApi`. I suggest you double-check the changes you did.

Also, be sure that you've actually loaded the changed version of the library, and that you're not importing a different one by accident. (For instance by placing an `assert False` in `ledgeraccounts.py` and confirm that you can trigger that, so you know your edits are picked up correctly.)

**Comment by RubenvZenden** [comment]
@wdoekes Sorry for my late response. Somehow the next day my code worked without making any changes. Thanks for responding.
