### ISSUE TITLE
Get actual dates from the fields 'Created' or 'Modified'

### ISSUE THREAD

**Issue by RubenvZenden** [ossobv/exactonline#32]
Hey, I want to keep track of the history of my data by the usage of 'Created' or 'Modified'. While importing these dates I get responses like this: 'Modified': '/Date(1488281267907)/'. Does someone has experience with this and knows how to get the actual date?  
When using Postman I do get normal dates in my response. 

If you know another way of keeping track of the history that is of course also welcome.

**Comment by wdoekes** [comment]
This is unixtime in milliseconds:
```python
>>> from time import gmtime
>>> gmtime(1488281267907 / 1000.0)
time.struct_time(tm_year=2017, tm_mon=2, tm_mday=28, tm_hour=11, tm_min=27, tm_sec=47, tm_wday=1, tm_yday=59, tm_isdst=0)
```

**Comment by RubenvZenden** [comment]
What I mean is that my data has history, so the original values from Created are okay, but somehow de response gotten from the code consist of dates like this '/Date(1488281267907)/' instead of for example 24-3-2021. 
The reason why I need this is that I can filter on a year and see how many hours my team has spent on a specific project.
I hope this clarifies it more.

**Comment by wdoekes** [comment]
> Does someone has experience with this and knows how to get the actual date?

I've shown you how to translate the javascript/json datestring into a time struct. That answers your question. This is not a how-to-program-in-python forum.
