### ISSUE TITLE
Basic logging

### ISSUE THREAD

**Issue by mhemeryck** [ossobv/exactonline#37]
Basic of the new exactonline rate limiting policy, we were forced to review the way we do outgoing calls to exactonline, specifically we were hitting a limit on the token renewals. After checking, it turns out that your client library already manages that part really well, it just needs a different approach to store the tokens (we pretty much faced the same issue as in #30 and ended up with the same solution: a cache-backed storage).

However, before going live with this, we would like to see the change in behavior in terms of outgoing calls to exactonline. Since all of these outgoing calls are done via this library, we can't simply add log entries.

Alternatives I did think of were:
* adding in a proxy:  difficult to support he initial authorization code flow, needs to be HTTPS
* doing a full mock API: seems overkill for this purpose

Hence my question: would you be OK if we would add some log lines into the code? I would just use the standard python logging library and I would add them at `debug` level.

**Comment by wdoekes** [comment]
Sure thing. Bonus points if you mask out secrets, unless they are relevant to your cause.
