### ISSUE TITLE
Exceeding rate limits unwrap.py

### ISSUE THREAD

**Issue by Thomasolicious** [ossobv/exactonline#40]
Hello,

I am struggling to keep my code running within [rate limits](https://support.exactonline.com/community/s/knowledge-base#All-All-DNO-Simulation-gen-apilimits). To my understanding, the function unwrap.py does nothing to control the amount of requests, is that correct? The minutely limit of 60 calls is easily exceeded when large amounts of pages are unwrapped right? Is there something I can do myself to keep everything in between limits?

Thanks in advance

**Comment by wdoekes** [comment]
You are correct, sir.

If you don't want automatic unwrapping, you can set the iteration_limit:

https://github.com/ossobv/exactonline/blob/d10e75e085d552591dd1dd1fdd300ff700bb89d0/exactonline/storage/base.py#L104

I don't think it's feasible to implement a generic solution to tackle API limits that fits everyones needs. Even if we add sleeps to limit the requests so we don't trip the API limits, we might hit them anyway if the same user runs multiple applications against the API.

However, for your case: if you don't mind the slowness, you could simply add a sleep(1) between every call. That should get you a 60 calls per minute max.:
```python
import time

class MySleep:
    def _rest_query(self, request):
        time.sleep(1)
        return super()._rest_query(request)

class MyExactApi(MySleep, ExactApi):
    pass
```
Something along those lines perhaps...?

Or, since we ideally do not want to change private/protected members (those starting with `_`), altering the `storage.get_access_token()` is also a solution.

As you can see in _rest_query, it is called for every request. So doing a sleep there would have the same effect.

**Comment by Thomasolicious** [comment]
Thank you for the elaboration! 

It indeed makes sense to fix rate limit issues on "call level". Thanks for thinking along with me, I will try to test your suggestions. I initially tested some use cases with time.sleep() implemented in combination with applying filters to slim down the results which gives reasonable results for now. Another possibility I will look into is the [ratelimit](https://pypi.org/project/ratelimit/) package.

**Comment by wdoekes** [comment]
:+1: 

Do let us know if you implement something that seems applicable for other users as well.

**Comment by robkorv** [comment]
Maybe something like HTTPAdapter with configurable urllib3.util.Retry?
Some examples https://findwork.dev/blog/advanced-usage-python-requests-timeouts-retries-hooks/

Retry docs: https://urllib3.readthedocs.io/en/latest/reference/urllib3.util.html#urllib3.util.Retry

**Comment by aukehuizinga** [comment]
The library could also check the `X-RateLimit-Remaining` and `X-RateLimit-Minutely-Remaining` values to determine if it should wait with querying.

There's even a `X-RateLimit-Reset` that can be checked for determining if the rate limit will be lifted soon. Although naming suggest that it is for the daily rate limit and not the minutely rate limit.

I know it can be hard to actually implement this in a way it's usable for everyone.

**Comment by wdoekes** [comment]
I committed something. I'll want to refactor that a bit, but it should be usable for a single caller.

It will probably need some 429 handling too.. for instance if you're (re)starting when the limits are reached.

**Comment by renewfrl** [comment]
you could implement a retry with backoff method. A basic one is this for example:

https://github.com/nameko/nameko/blob/master/nameko/utils/retry.py

and then annotate the function with:

`    @retry(delay=5, max_attempts=3, backoff=2)
`

or if you want to specific filter for 422 you could do some like
```
        max_attempts=3,
        delay=10,
        backoff=2,
        for_exceptions=(TooManyRequests, ServerException503))
```

(I changed the client a little bit to cast a 422 into a TooManyRequest exception to keep the code readable)

**Comment by wdoekes** [comment]
I think things should work now.

Let me know if anything is amiss.

(Yes, it greatly helps coding priority when I'm affected by the ratelimits myself :P )

**Comment by Thomasolicious** [comment]
Although everything went well for almost 4 months, as of today I'm again batteling rate limits (HTTPError: Too Many Requests). I initially reduced my number of requests and added more time.sleep()'s in between requests and you updated your code as well. 

Are there others encountering the same problems as I am?

**Comment by wdoekes** [comment]
> Are there others encountering the same problems as I am?

I haven't noticed anything. But we only do a single cron job in the morning.

Did you use the latest code? Additional sleep should not be necessary, unless you're running multiple processes at the same time of course.

**Comment by Thomasolicious** [comment]
Updated this morning from 0.3.5 to 0.3.6, ran my code afterwards and found the same issue. I am using the sleep between multiple requests to stay under the allowed 60 call per minute.

**Comment by wdoekes** [comment]
The fixes are not in a released version. So if you're using 0.3.6, you're not getting the rate limiter fixes.

See the commit log:
https://github.com/ossobv/exactonline/commits

And compare:
https://github.com/ossobv/exactonline/commit/4962a45637281d582be37eda901bfd7d4d56d2d7
which lists a tag (0.3.6)
and
https://github.com/ossobv/exactonline/commit/bf62468d0c7928cdf8c7134de60ae6f154540b8a
which is only available in master.

**Comment by wdoekes** [comment]
```
pip install git+https://github.com/ossobv/exactonline.git@master
```
methinks

**Comment by Thomasolicious** [comment]
Many thanks!! I just ran my code and found no issues anymore

**Comment by wdoekes** [comment]
:ok_hand:
